_G.CloneClass(IngameWaitingForPlayersState)
function IngameWaitingForPlayersState:at_exit(...)
    IngameWaitingForPlayersState.orig.at_exit(self, ...)

    UT.Dexterity:setGodMode(UT:getSetting("enable_god_mode"), false)
    UT.Dexterity:setInfiniteStamina(UT:getSetting("enable_infinite_stamina"))
    UT.Dexterity:setNoclip(UT:getSetting("enable_noclip"), true, false)
    UT.Dexterity:setRunInAllDirections(UT:getSetting("enable_run_in_all_directions"))
    UT.Dexterity:setCanRunWithAnyBag(UT:getSetting("enable_can_run_with_any_bag"))
    UT.Dexterity:setFastMask(UT:getSetting("enable_fast_mask"))
    UT.Dexterity:setNoCarryCooldown(UT:getSetting("enable_no_carry_cooldown"))
    UT.Dexterity:setNoFlashbangs(UT:getSetting("enable_no_flashbangs"))
    UT.Dexterity:setInstantSwap(UT:getSetting("enable_instant_swap"))
    UT.Dexterity:setInstantReload(UT:getSetting("enable_instant_reload"))
    UT.Dexterity:setShootThroughWalls(UT:getSetting("enable_shoot_through_walls"), false)
    UT.Dexterity:setNoRecoil(UT:getSetting("enable_no_recoil"))
    UT.Dexterity:setNoSpread(UT:getSetting("enable_no_spread"))
    UT.Dexterity:setUnlimitedAmmo(UT:getSetting("enable_unlimited_ammo"))
    UT.Dexterity:setInstantInteraction(UT:getSetting("enable_instant_interaction"))
    UT.Dexterity:setInstantDeployment(UT:getSetting("enable_instant_deployment"))
    UT.Dexterity:setUnlimitedEquipment(UT:getSetting("enable_unlimited_equipment"))
    UT.Dexterity:setMoveSpeedMultiplier(UT:getSetting("enable_move_speed_multiplier"), UT:getSetting("move_speed_multiplier"))
    UT.Dexterity:setThrowDistanceMultiplier(UT:getSetting("enable_throw_distance_multiplier"), UT:getSetting("throw_distance_multiplier"))
    UT.Dexterity:setFireRateMultiplier(UT:getSetting("enable_fire_rate_multiplier"), UT:getSetting("fire_rate_multiplier"))
    UT.Dexterity:setDamageMultiplier(UT:getSetting("enable_damage_multiplier"), UT:getSetting("damage_multiplier"))
end

